---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: prosto
description: Experimental OS with Fedora + Pantheon.

base-image: ghcr.io/blue-build/base-images/fedora-base
alt-tags:
  - latest
image-version: 43

modules:
  - from-file: ../modules/common.yml
  - type: signing
