---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: prosto
# description will be included in the image's metadata
description: Experimental OS with Fedora + Pantheon.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - garaevdi/pantheon-rpm
    install:
      packages:
        - appcenter
        - elementary-dock
        - elementary-greeter
        - elementary-settings
        - elementary-shortcut-overlay
        - elementary-sideload
        - elementary-terminal
        - elementary-files
        - gala
        - pantheon-agent-polkit
        - pantheon-session-settings
        - plymouth-theme-elementary
        - switchboard
        - wingpanel
        - xdg-desktop-portal-pantheon
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - notify: true
        scope: system
        repo: 
          tilte: elementary
          url: https://flatpak.elementary.io/repo.flatpakrepo
        install:
          - io.elementary.calculator
          - io.elementary.calendar
          - io.elementary.camera
          - io.elementary.capnet-assist
          - io.eleemntary.contacts
          - io.eleemntary.iconbrowser
          - io.elementary.mail
          - io.elementary.maps
          - io.elementary.music
          - io.elementary.photos
          - io.elementary.screenshot
          - io.elementary.tasks
          - io.elementary.videos
          - org.gnome.Epiphany
          - org.gnome.Evince
          - org.gnome.FileRoller
          - org.gnome.font-viewer
      - scope: user # Also add Flathub user repo, but no user packages

  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
