name: prosto
min-version: 2.7
element-path: elements

source-caches:
- url: https://gbm.gnome.org:11003
  connection-config:
    keepalive-time: 60
    retry-limit: 5
    retry-delay: 500
    request-timeout: 100

fatal-warnings:
- overlaps
- unaliased-url
- unstages-files

(@):
- gnome-build-meta.bst:freedesktop-sdk.bst:include/runtime.yml
- gnome-build-meta.bst:include/aliases.yml
- gnome-build-meta.bst:include/mirrors.yml
- gnome-build-meta.bst:include/shell.yml
- include/aliases.yml

environment:
  LC_ALL: en_US.UTF-8

variables:
  (@):
  - include/image-version.yml

split-rules:
  devel:
    (>):
    - "%{indep-libdir}/**/include"
    - "%{indep-libdir}/**/include/**"
    - "%{bindir}/*-config"
    - "%{libdir}/cmake"
    - "%{libdir}/cmake/**"
    - "%{datadir}/cmake"
    - "%{datadir}/cmake/**"
    - "%{datadir}/gir-1.0"
    - "%{datadir}/gir-1.0/**"
    - "%{datadir}/vala*/vapi"
    - "%{datadir}/vala*/vapi/**"
    - "%{datadir}/installed-tests"
    - "%{datadir}/installed-tests/**"
    - "%{libexecdir}/installed-tests"
    - "%{libexecdir}/installed-tests/**"
  doc:
    (>):
    - "%{datadir}/gtk-doc/html"
    - "%{datadir}/gtk-doc/html/**"
  source:
  - "%{sourcedir}"
  - "%{sourcedir}/**"
  vm:
  - "%{datadir}/dbus-1/**"

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  elements:
  - meson
  - make
  sources:
  - patch
- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  elements:
  - collect_manifest
  sources:
  - git_repo
  - git_module
- origin: junction
  junction: gnome-build-meta.bst
  elements:
  - collect_initial_scripts

junctions:
  internal:
  - plugins/buildstream-plugins.bst
  - plugins/buildstream-plugins-community.bst
